trigger:
- master

queue: Hosted VS2017

steps:
- powershell: .\build.ps1
  displayName: Build
  
- task: PublishBuildArtifacts@1
  displayName: Publish Website Artifacts
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)\output.zip'
    artifactType: container
    artifactName: Packages
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
